/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.egresados.vista.gui;

import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Departamento;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Egresado;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Pais;
import co.edu.eam.ingesoft.egresados.vista.controladores.ControladorEmpleadosEmpresa;
import java.awt.Color;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanegas
 */
public class VentanaEmpleadosEmpresa extends javax.swing.JFrame {

	/**
	 * controlador de la ventana donde se encuentra las operaciones logicas de empresa
	 */
	private ControladorEmpleadosEmpresa controlador;

	/**
	 * Creates new form VentanaEmpleadosEmpresa
	 */
	public VentanaEmpleadosEmpresa() {
		initComponents();
		this.getContentPane().setBackground(Color.GREEN);
		controlador = new ControladorEmpleadosEmpresa();
		try {
			llenarComboEmpresa();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Método para llenar el combo de departamentos
	 * 
	 * @param pais,
	 *            el pais al cual pertenecen los departamentos
	 * @throws Exception
	 */
	private void llenarComboEmpresa() throws Exception {
		cbEmpresa.removeAllItems();
		List<Empresa> lista = controlador.listarEmpresa();
		cbEmpresa.addItem("Seleccione una empresa");
		for (Empresa empresita : lista) {
			cbEmpresa.addItem(empresita);
		}
	}

	/**
	 * Metodo para llenas la tabla de Reportes del egresado
	 * @param emp, empresa por la cual se listaran los egresados
	 */
	public void llenartabla(Empresa emp) {

		try {
			List<Egresado> lista = controlador.listarEgresadosPorEmpresa(emp);

			DefaultTableModel dtm = (DefaultTableModel) tablaEgresados.getModel();
			dtm.setRowCount(0);
			for (Egresado egre : lista) {
				dtm.addRow(new Object[] { egre.getNombre(), egre.getPrograma().getNombre(),
						egre.getInfoLaboral().getCargoEmpresa(), egre.getInfoLaboral().getFechaIngreso() });
			}

		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tablaEgresados = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		btnReporte = new javax.swing.JButton();
		cbEmpresa = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		tablaEgresados.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null }, { null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } },
				new String[] { "Nombre", "Programa", "Cargo", "Fecha de entrada" }));
		jScrollPane1.setViewportView(tablaEgresados);

		jPanel2.setBackground(new java.awt.Color(0, 153, 0));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jLabel2.setText("Nombre de empresa:");

		btnReporte.setText("GENERAR REPORTE");
		btnReporte.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnReporteActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
						.addGap(18, 18, 18)
						.addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 169,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnReporte)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(btnReporte).addComponent(cbEmpresa,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(31, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado22.png"))); // NOI18N
		jLabel1.setText("Registro de empleados por empresa");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(22, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1).addGap(162, 162, 162)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(35, 35, 35).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(19, 19, 19)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReporteActionPerformed
		// TODO add your handling code here:
		Empresa emp = (Empresa) cbEmpresa.getSelectedItem();
		if (cbEmpresa.getSelectedIndex() == 0) {
			JOptionPane.showMessageDialog(null, "Debe seleccionar una empresa");
		} else {
			llenartabla(emp);
		}
	}// GEN-LAST:event_btnReporteActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnReporte;
	private javax.swing.JComboBox cbEmpresa;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablaEgresados;
	// End of variables declaration//GEN-END:variables
}
