/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.egresados.vista.gui;

import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Ciudad;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Contacto;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Departamento;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Pais;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.SectorLaboral;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.TipoEmpresaEnum;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.egresados.vista.controladores.ControladorVentanaRegistroEmpresa;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Sala409_Pc18
 */
public class VentanaRegistroEmpresa extends javax.swing.JFrame implements ActionListener {

	/**
	 * El controlador de la ventana Registro Empresa
	 */
	private ControladorVentanaRegistroEmpresa controlador;

	/**
	 * Creates new form VentanaRegistroEmpresa
	 */
	public VentanaRegistroEmpresa() {
	
		initComponents();
		this.getContentPane().setBackground(Color.BLUE);
		btnAtras.addActionListener(this);
		btnSiguiente.addActionListener(this);
		btnCancelar.addActionListener(this);
		btnGuardar.addActionListener(this);
		btnGuardar.setVisible(false);
		btnAtras.setVisible(false);
		cargarTipoEmpresa();
		controlador = new ControladorVentanaRegistroEmpresa();
		try {
			cargarComboPais();
			cargarComboSectorLaboral();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void cargarTipoEmpresa() {
		for (TipoEmpresaEnum lista : TipoEmpresaEnum.values()) {
			cbTipoEmpresa.addItem(lista);
		}
	}

	/**
	 * Método para llenar el combo de departamentos
	 * 
	 * @param pais,
	 *            el pais al cual pertenecen los departamentos
	 * @throws Exception
	 */
	private void llenarComboDepartmaneto(Pais pais) throws Exception {
		cbDepartamento.removeAllItems();
		List<Departamento> deptos = controlador.listarDepartamentosPorPais(pais);
		cbDepartamento.addItem("Seleccione un departamento");
		for (Departamento depto : deptos) {
			cbDepartamento.addItem(depto);
		}
	}

	/**
	 * Método para llenar el combo de ciudades
	 * 
	 * @param depto,
	 *            el departamento al cual pertenecen las ciudades
	 * @throws Exception
	 */
	private void llenarComboCiudad(Departamento depto) throws Exception {
		cbCiudad.removeAllItems();
		List<Ciudad> ciudades = controlador.listarCiudadPorDepartamento(depto);
		cbCiudad.addItem("Seleccione una ciudad");
		for (Ciudad ciudad : ciudades) {
			cbCiudad.addItem(ciudad);
		}
	}

	/**
	 * Método para llenar el combo de pais
	 * 
	 * @throws Exception
	 */
	private void cargarComboPais() throws Exception {
		// cbPais.removeAllItems();
		List<Pais> paises = controlador.listarPais();
		cbPais.addItem("Seleccione un pais");
		for (Pais pais : paises) {
			cbPais.addItem(pais);
		}
	}

	/**
	 * Método para llenar el combo de sector laboral
	 * 
	 * @throws Exception
	 */
	private void cargarComboSectorLaboral() throws Exception {
		// cbPais.removeAllItems();
		List<SectorLaboral> sectores = controlador.listarSectoresLaborales();
		cbSectorLaboral.addItem("Seleccione un sector laboral");
		for (SectorLaboral sector : sectores) {
			cbSectorLaboral.addItem(sector);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jTBPrincipal = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfRazonSocial = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		cbPais = new javax.swing.JComboBox();
		tfNit = new javax.swing.JTextField();
		tfTelefonoEmpresa = new javax.swing.JTextField();
		cbDepartamento = new javax.swing.JComboBox();
		cbCiudad = new javax.swing.JComboBox();
		tfFax = new javax.swing.JTextField();
		cbTipoEmpresa = new javax.swing.JComboBox();
		tfDireccion = new javax.swing.JTextField();
		cbSectorLaboral = new javax.swing.JComboBox();
		tfSitioWeb = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jLabel16 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		tfCorreo = new javax.swing.JTextField();
		tfCargo = new javax.swing.JTextField();
		tfTelefonoContacto = new javax.swing.JTextField();
		jLPaso = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		btnCancelar = new javax.swing.JButton();
		btnAtras = new javax.swing.JButton();
		btnSiguiente = new javax.swing.JButton();
		btnGuardar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 153, 51));
		setResizable(false);

		jPanel3.setBackground(new java.awt.Color(0, 0, 255));

		jTBPrincipal.setEnabled(false);

		jPanel2.setBackground(new java.awt.Color(0, 102, 204));

		jLabel1.setText("Razon Social *");

		jLabel2.setText("Pais *");

		jLabel3.setText("Telefono *");

		jLabel4.setText("Nit *");

		jLabel5.setText("Departamento *");

		jLabel6.setText("Fax *");

		jLabel7.setText("Tipo de Empresa *");

		jLabel8.setText("Ciudad *");

		jLabel9.setText("Direccion Sitio Web *");

		jLabel10.setText("Sector Laboral *");

		jLabel11.setText("Direccion *");

		cbPais.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cbPaisItemStateChanged(evt);
			}
		});

		cbDepartamento.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cbDepartamentoItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel2Layout.createSequentialGroup().addGap(49, 49, 49)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel10).addComponent(jLabel1)
														.addComponent(jLabel7)
														.addComponent(cbTipoEmpresa, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(tfNit)
														.addComponent(tfRazonSocial,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4).addComponent(cbSectorLaboral, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(62, 62, 62)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addGroup(jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel2)
																						.addComponent(jLabel5)
																						.addComponent(jLabel8))
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addGroup(jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(cbDepartamento,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0, 189, Short.MAX_VALUE)
																						.addComponent(cbCiudad, 0, 0,
																								Short.MAX_VALUE)
																						.addComponent(cbPais, 0, 0,
																								Short.MAX_VALUE))
																				.addGap(76, 76, 76)))
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel6).addComponent(jLabel3)
																		.addComponent(jLabel9)
																		.addComponent(tfSitioWeb,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(tfFax,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(tfTelefonoEmpresa,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel11)
																		.addComponent(tfDireccion,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				159,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		216, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(56, 56, 56)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(25, 25, 25).addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(13, 13, 13).addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(tfNit, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
								.addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel5)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel8)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
								.addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel6)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel9)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(
										tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel10).addComponent(jLabel11))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(cbSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(41, Short.MAX_VALUE)));

		jTBPrincipal.addTab("1. Datos de la empresa", jPanel2);

		jPanel4.setBackground(new java.awt.Color(0, 102, 204));

		jLabel16.setText("Nombre Completo *");

		jLabel18.setText("Correo Electronico *");

		jLabel19.setText("Cargo en la empresa *");

		jLabel20.setText("Telefono *");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(35, 35, 35).addGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(
												jPanel4Layout.createSequentialGroup()
														.addGroup(jPanel4Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel16).addComponent(jLabel19))
														.addGap(168, 168, 168))
										.addGroup(jPanel4Layout.createSequentialGroup().addComponent(tfNombre)
												.addGap(75, 75, 75)))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 201,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(75, 75, 75)))
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel20).addComponent(jLabel18).addComponent(tfCorreo).addComponent(
										tfTelefonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
						.addContainerGap(219, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel16).addComponent(jLabel18))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(42, 42, 42)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel19).addComponent(jLabel20))
						.addGap(18, 18, 18)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tfTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(117, Short.MAX_VALUE)));

		jTBPrincipal.addTab("2. Datos de contacto", jPanel4);

		jLPaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lab-technician.png"))); // NOI18N
		jLPaso.setText("Paso 1/2");
		jLPaso.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maleta.png"))); // NOI18N
		jLabel17.setText("Registro de empresa");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jLabel17).addGap(176, 176, 176).addComponent(jLPaso)
												.addGap(28, 28, 28))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(jTBPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 730,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 25, Short.MAX_VALUE)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel3Layout.createSequentialGroup().addGap(13, 13, 13)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel17).addComponent(jLPaso))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTBPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 314,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(39, Short.MAX_VALUE)));

		btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
		btnCancelar.setText("CANCELAR");

		btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/left-arrow.png"))); // NOI18N
		btnAtras.setText("ATRAS");

		btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/right-arrow.png"))); // NOI18N
		btnSiguiente.setText("SIGUIENTE");

		btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
		btnGuardar.setText("GUARDAR");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addGap(10, 10, 10).addComponent(btnCancelar)
												.addGap(67, 67, 67).addComponent(btnAtras)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnSiguiente).addGap(77, 77, 77).addComponent(btnGuardar)
												.addGap(76, 76, 76))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(47, 47, 47)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(9, 9, 9)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnCancelar).addComponent(btnAtras).addComponent(btnSiguiente)
								.addComponent(btnGuardar))
						.addContainerGap(20, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cbPaisItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbPaisItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbPais.getSelectedItem() == null) {
				return;
			}
			if (cbPais.getSelectedIndex() != 0) {
				llenarComboDepartmaneto((Pais) cbPais.getSelectedItem());
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}
	}// GEN-LAST:event_cbPaisItemStateChanged

	private void cbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbDepartamentoItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbDepartamento.getSelectedItem() == null) {
				return;
			}
			if (cbDepartamento.getSelectedIndex() != 0) {
				llenarComboCiudad((Departamento) cbDepartamento.getSelectedItem());
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}
	}// GEN-LAST:event_cbDepartamentoItemStateChanged

	public void limpiarCampos() {
		tfCargo.setText(null);
		tfCorreo.setText(null);
		tfDireccion.setText(null);
		tfFax.setText(null);
		tfNit.setText(null);
		tfNombre.setText(null);
		tfRazonSocial.setText(null);
		tfSitioWeb.setText(null);
		tfTelefonoContacto.setText(null);
		tfTelefonoEmpresa.setText(null);
		cbCiudad.setSelectedIndex(0);
		cbDepartamento.setSelectedIndex(0);
		cbPais.setSelectedIndex(0);
		cbSectorLaboral.setSelectedIndex(0);
		cbTipoEmpresa.setSelectedIndex(0);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAtras;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnGuardar;
	private javax.swing.JButton btnSiguiente;
	private javax.swing.JComboBox cbCiudad;
	private javax.swing.JComboBox cbDepartamento;
	private javax.swing.JComboBox cbPais;
	private javax.swing.JComboBox cbSectorLaboral;
	private javax.swing.JComboBox cbTipoEmpresa;
	private javax.swing.JLabel jLPaso;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTabbedPane jTBPrincipal;
	private javax.swing.JTextField tfCargo;
	private javax.swing.JTextField tfCorreo;
	private javax.swing.JTextField tfDireccion;
	private javax.swing.JTextField tfFax;
	private javax.swing.JTextField tfNit;
	private javax.swing.JTextField tfNombre;
	private javax.swing.JTextField tfRazonSocial;
	private javax.swing.JTextField tfSitioWeb;
	private javax.swing.JTextField tfTelefonoContacto;
	private javax.swing.JTextField tfTelefonoEmpresa;
	// End of variables declaration//GEN-END:variables

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == btnAtras) {
			jLPaso.setText("Paso 1/2");
			jTBPrincipal.setSelectedIndex(0);
			btnSiguiente.setVisible(true);
			btnGuardar.setVisible(false);
			btnAtras.setVisible(false);

		}
		if (e.getSource() == btnSiguiente) {
			jLPaso.setText("Paso 2/2");
			jTBPrincipal.setSelectedIndex(1);
			btnAtras.setVisible(true);
			btnGuardar.setVisible(true);
			btnSiguiente.setVisible(false);

		}

		if (e.getSource() == btnCancelar) {
			limpiarCampos();
			jTBPrincipal.setSelectedIndex(0);
			btnAtras.setVisible(false);
			btnGuardar.setVisible(false);
			btnSiguiente.setVisible(true);
		}

		if (e.getSource() == btnGuardar) {
			try {
				// Validar que los campos no esten vacios
				if (tfRazonSocial.getText().isEmpty() || tfNit.getText().isEmpty() || cbCiudad.getSelectedIndex() == 0
						|| tfDireccion.getText().isEmpty() || tfTelefonoEmpresa.getText().isEmpty()
						|| tfFax.getText().isEmpty() || tfSitioWeb.getText().isEmpty() || tfNombre.getText().isEmpty()
						|| tfCorreo.getText().isEmpty() || tfCargo.getText().isEmpty()
						|| tfTelefonoContacto.getText().isEmpty()) {

					JOptionPane.showMessageDialog(null, "Debe completar todos los campos");

				} else {
					String razon = tfRazonSocial.getText();
					String nit = tfNit.getText();
					TipoEmpresaEnum tipoEmpresa = (TipoEmpresaEnum) cbTipoEmpresa.getSelectedItem();
					SectorLaboral sector = (SectorLaboral) cbSectorLaboral.getSelectedItem();
//					Pais p = (Pais) cbPais.getSelectedItem();
//					Departamento d = (Departamento) cbDepartamento.getSelectedItem();
//					d.setPais(p);
					Ciudad ciudad = (Ciudad) cbCiudad.getSelectedItem();
					//ciudad.setDepartamento(d);
					String direccion = tfDireccion.getText();
					String telEmpresa = tfTelefonoEmpresa.getText();
					String fax = tfFax.getText();
					String sitioWeb = tfSitioWeb.getText();

					String nomCompleto = tfNombre.getText();
					String correo = tfCorreo.getText();
					String cargo = tfCargo.getText();
					String telContacto = tfTelefonoContacto.getText();
					Contacto contacto = new Contacto(nit, nomCompleto, correo, cargo, telContacto);
					Empresa empresa = new Empresa(nit, sector, ciudad, contacto, razon, telEmpresa, tipoEmpresa, fax,
							sitioWeb, direccion);
					contacto.setEmpresa(empresa);
					//controlador.crearContacto(contacto);
					controlador.crearEmpresa(empresa);
					JOptionPane.showMessageDialog(null, "Se creo correctamente la empresa");
				}
			} catch (ExcepcionNegocio e1) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(null, e1.getMessage());
				e1.printStackTrace();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
	}
}
