/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.egresados.vista.gui;

import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Ciudad;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Contacto;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Departamento;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Pais;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.SectorLaboral;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.TipoEmpresaEnum;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.egresados.vista.controladores.ControladorVentanaEditarEmpresa;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Sala409_Pc18
 */
public class VentanaEditarEmpresa extends javax.swing.JFrame implements ActionListener {

	/**
	 * El controlador de la ventana Editar Empresa
	 */
	private ControladorVentanaEditarEmpresa controlador;

	/**
	 * Creates new form VentanaRegistroEmpresa
	 */
	public VentanaEditarEmpresa() {
		controlador = new ControladorVentanaEditarEmpresa();
		initComponents();
		this.getContentPane().setBackground(Color.BLUE);
		btnAtras.addActionListener(this);
		btnSiguiente.addActionListener(this);
		btnBuscar.addActionListener(this);
		btnEditar.addActionListener(this);
		cargarTipoEmpresa();
		try {
			cargarComboPais();
			cargarComboSectorLaboral();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * Metodo para cargar el combobox de tipo de empresa
	 */
	public void cargarTipoEmpresa() {
		for (TipoEmpresaEnum lista : TipoEmpresaEnum.values()) {
			cbTipoEmpresa.addItem(lista);
		}
	}

	/**
	 * Método para llenar el combo de departamentos
	 * 
	 * @param pais,
	 *            el pais al cual pertenecen los departamentos
	 * @throws Exception
	 */
	private void llenarComboDepartmaneto(Pais pais) throws Exception {
		cbDepartamento.removeAllItems();
		List<Departamento> deptos = controlador.listarDepartamentosPorPais(pais);
		cbDepartamento.addItem("Seleccione un departamento");
		for (Departamento depto : deptos) {
			cbDepartamento.addItem(depto);
		}
	}

	/**
	 * Método para llenar el combo de ciudades
	 * 
	 * @param depto,
	 *            el departamento al cual pertenecen las ciudades
	 * @throws Exception
	 */
	private void llenarComboCiudad(Departamento depto) throws Exception {
		cbCiudad.removeAllItems();
		List<Ciudad> ciudades = controlador.listarCiudadPorDepartamento(depto);
		cbCiudad.addItem("Seleccione una ciudad");
		for (Ciudad ciudad : ciudades) {
			cbCiudad.addItem(ciudad);
		}
	}

	/**
	 * Método para llenar el combo de pais
	 * 
	 * @throws Exception
	 */
	private void cargarComboPais() throws Exception {
		// cbPais.removeAllItems();
		List<Pais> paises = controlador.listarPais();
		cbPais.addItem("Seleccione un pais");
		for (Pais pais : paises) {
			cbPais.addItem(pais);
		}
	}

	/**
	 * Método para llenar el combo de sector laboral
	 * 
	 * @throws Exception
	 */
	private void cargarComboSectorLaboral() throws Exception {
		// cbPais.removeAllItems();
		List<SectorLaboral> sectores = controlador.listarSectoresLaborales();
		cbSectorLaboral.addItem("Seleccione un sector laboral");
		for (SectorLaboral sector : sectores) {
			cbSectorLaboral.addItem(sector);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jTBPrincipal = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfRazonSocial = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		cbPais = new javax.swing.JComboBox();
		tfNit = new javax.swing.JTextField();
		tfTelefonoEmpresa = new javax.swing.JTextField();
		cbDepartamento = new javax.swing.JComboBox();
		cbCiudad = new javax.swing.JComboBox();
		tfFax = new javax.swing.JTextField();
		cbTipoEmpresa = new javax.swing.JComboBox();
		tfDireccion = new javax.swing.JTextField();
		cbSectorLaboral = new javax.swing.JComboBox();
		tfSitioWeb = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		tfCorreo = new javax.swing.JTextField();
		tfCargo = new javax.swing.JTextField();
		tfTelefonoContacto = new javax.swing.JTextField();
		jLPaso = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		btnBuscar = new javax.swing.JButton();
		btnAtras = new javax.swing.JButton();
		btnSiguiente = new javax.swing.JButton();
		btnEditar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 153, 51));
		setResizable(false);

		jPanel3.setBackground(new java.awt.Color(0, 0, 255));

		jTBPrincipal.setEnabled(false);

		jPanel2.setBackground(new java.awt.Color(0, 102, 204));

		jLabel1.setText("Razon Social *");

		jLabel2.setText("Pais *");

		jLabel3.setText("Telefono *");

		jLabel4.setText("Nit *");

		jLabel5.setText("Departamento *");

		jLabel6.setText("Fax *");

		jLabel7.setText("Tipo de Empresa *");

		jLabel8.setText("Ciudad *");

		jLabel9.setText("Direccion Sitio Web *");

		jLabel10.setText("Sector Laboral *");

		jLabel11.setText("Direccion *");

		cbPais.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cbPaisItemStateChanged(evt);
			}
		});

		cbDepartamento.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cbDepartamentoItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(
						jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel2Layout.createSequentialGroup().addGap(49, 49, 49)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel10).addComponent(jLabel1)
														.addComponent(jLabel7)
														.addComponent(cbTipoEmpresa, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(tfNit)
														.addComponent(tfRazonSocial,
																javax.swing.GroupLayout.PREFERRED_SIZE, 153,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4).addComponent(cbSectorLaboral, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(62, 62, 62)
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addGroup(jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel2)
																						.addComponent(jLabel5)
																						.addComponent(jLabel8))
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																		.addGroup(jPanel2Layout.createSequentialGroup()
																				.addGroup(jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(cbDepartamento,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0, 0, Short.MAX_VALUE)
																						.addComponent(cbCiudad, 0, 0,
																								Short.MAX_VALUE)
																						.addComponent(cbPais, 0, 0,
																								Short.MAX_VALUE))
																				.addGap(76, 76, 76)))
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel6).addComponent(jLabel3)
																		.addComponent(jLabel9)
																		.addComponent(tfSitioWeb,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(tfFax,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(tfTelefonoEmpresa,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addGroup(jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel11)
																		.addComponent(tfDireccion,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				159,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		216, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(56, 56, 56)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(25, 25, 25).addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(13, 13, 13).addComponent(jLabel4)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(tfNit, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
								.addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel5)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel8)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(cbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
								.addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfTelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel6)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel9)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(tfSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(
										tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel10).addComponent(jLabel11))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(cbSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jTBPrincipal.addTab("1. Datos de la empresa", jPanel2);

		jPanel1.setBackground(new java.awt.Color(0, 102, 204));

		jLabel12.setText("Nombre Completo *");

		jLabel13.setText("Correo Electronico *");

		jLabel14.setText("Cargo en la empresa *");

		jLabel15.setText("Telefono *");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(35, 35, 35).addGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(
												jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel12).addComponent(jLabel14))
														.addGap(168, 168, 168))
										.addGroup(jPanel1Layout.createSequentialGroup().addComponent(tfNombre)
												.addGap(75, 75, 75)))
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 201,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(75, 75, 75)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel15).addComponent(jLabel13).addComponent(tfCorreo).addComponent(
										tfTelefonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
						.addContainerGap(202, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(30, 30, 30)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel12).addComponent(jLabel13))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(42, 42, 42)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel14).addComponent(jLabel15))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(tfCargo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(tfTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(117, Short.MAX_VALUE)));

		jTBPrincipal.addTab("2. Datos de contacto", jPanel1);

		jLPaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lab-technician.png"))); // NOI18N
		jLPaso.setText("Paso 1/2");
		jLPaso.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contratoww.png"))); // NOI18N
		jLabel17.setText("Editor de empresa");

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
		btnBuscar.setText("BUSCAR");

		btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/left-arrow.png"))); // NOI18N
		btnAtras.setText("ATRAS");

		btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/right-arrow.png"))); // NOI18N
		btnSiguiente.setText("SIGUIENTE");

		btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
		btnEditar.setText("EDITAR");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jTBPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup().addComponent(jLabel17)
												.addGap(143, 143, 143).addComponent(jLPaso).addGap(30, 30, 30))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup().addComponent(btnBuscar).addGap(38, 38, 38)
												.addComponent(btnAtras).addGap(36, 36, 36).addComponent(btnSiguiente)
												.addGap(40, 40, 40).addComponent(btnEditar).addGap(73, 73, 73)))));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel3Layout.createSequentialGroup().addGap(25, 25, 25)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLPaso).addComponent(jLabel17))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jTBPrincipal)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnBuscar).addComponent(btnAtras).addComponent(btnSiguiente)
										.addComponent(btnEditar))
								.addGap(21, 21, 21)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24).addComponent(jPanel3,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(23, 23, 23)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void cbPaisItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbPaisItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbPais.getSelectedItem() == null) {
				return;
			}
			if (cbPais.getSelectedIndex() != 0) {
				llenarComboDepartmaneto((Pais) cbPais.getSelectedItem());
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}
	}// GEN-LAST:event_cbPaisItemStateChanged

	private void cbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbDepartamentoItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbDepartamento.getSelectedItem() == null) {
				return;
			}
			if (cbDepartamento.getSelectedIndex() != 0) {
				llenarComboCiudad((Departamento) cbDepartamento.getSelectedItem());
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}

	}// GEN-LAST:event_cbDepartamentoItemStateChanged

	/**
	 * Metodo para limpias los campos del formulario
	 */
	public void limpiarCampos() {
		tfCargo.setText(null);
		tfCorreo.setText(null);
		tfDireccion.setText(null);
		tfFax.setText(null);
		tfNit.setText(null);
		tfNombre.setText(null);
		tfRazonSocial.setText(null);
		tfSitioWeb.setText(null);
		tfTelefonoContacto.setText(null);
		tfTelefonoEmpresa.setText(null);
		cbCiudad.setSelectedIndex(0);
		cbDepartamento.setSelectedIndex(0);
		cbPais.setSelectedIndex(0);
		cbSectorLaboral.setSelectedIndex(0);
		cbTipoEmpresa.setSelectedIndex(0);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAtras;
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnEditar;
	private javax.swing.JButton btnSiguiente;
	private javax.swing.JComboBox cbCiudad;
	private javax.swing.JComboBox cbDepartamento;
	private javax.swing.JComboBox cbPais;
	private javax.swing.JComboBox cbSectorLaboral;
	private javax.swing.JComboBox cbTipoEmpresa;
	private javax.swing.JLabel jLPaso;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTabbedPane jTBPrincipal;
	private javax.swing.JTextField tfCargo;
	private javax.swing.JTextField tfCorreo;
	private javax.swing.JTextField tfDireccion;
	private javax.swing.JTextField tfFax;
	private javax.swing.JTextField tfNit;
	private javax.swing.JTextField tfNombre;
	private javax.swing.JTextField tfRazonSocial;
	private javax.swing.JTextField tfSitioWeb;
	private javax.swing.JTextField tfTelefonoContacto;
	private javax.swing.JTextField tfTelefonoEmpresa;
	// End of variables declaration//GEN-END:variables

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == btnAtras) {
			jLPaso.setText("Paso 1/2");
			jTBPrincipal.setSelectedIndex(0);
		}
		if (e.getSource() == btnSiguiente) {
			jLPaso.setText("Paso 2/2");
			jTBPrincipal.setSelectedIndex(1);
		}

		if (e.getSource() == btnBuscar) {
			try {
				if (tfNit.getText().isEmpty()) {

					JOptionPane.showMessageDialog(null, "Debe ingresa el codigo nit de la empresa a buscar");
					
				} else {
					String nit = tfNit.getText();
					Empresa emp = controlador.buscarEmpresa(nit);
					if (nit != null) {
						tfRazonSocial.setText(emp.getRazonSocial());
						cbTipoEmpresa.setSelectedItem(emp.getTipoEmpresa());
						cbSectorLaboral.setSelectedItem(emp.getSector());
						cbPais.setSelectedItem(emp.getCiudad().getDepartamento().getPais());
						cbDepartamento.setSelectedItem(emp.getCiudad().getDepartamento());
						cbCiudad.setSelectedItem(emp.getCiudad());
						tfDireccion.setText(emp.getDireccion());
						tfTelefonoEmpresa.setText(emp.getTel());
						tfFax.setText(emp.getFax());
						tfSitioWeb.setText(emp.getSitioWeb());
						tfNombre.setText(emp.getContacto().getNombreCompleto());
						tfCorreo.setText(emp.getContacto().getCorreo());
						tfCargo.setText(emp.getContacto().getCargoEmpresa());
						tfTelefonoContacto.setText(emp.getContacto().getTelefono());
					}
				}
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}

		}

		if (e.getSource() == btnEditar) {
			try {
				String razon = tfRazonSocial.getText();
				String nit = tfNit.getText();
				TipoEmpresaEnum tipoEmpresa = (TipoEmpresaEnum) cbTipoEmpresa.getSelectedItem();
				SectorLaboral sector = (SectorLaboral) cbSectorLaboral.getSelectedItem();
				Pais p = (Pais) cbPais.getSelectedItem();
				Departamento d = (Departamento) cbDepartamento.getSelectedItem();
				d.setPais(p);
				Ciudad ciudad = (Ciudad) cbCiudad.getSelectedItem();
				ciudad.setDepartamento(d);
				String direccion = tfDireccion.getText();
				String telEmpresa = tfTelefonoEmpresa.getText();
				String fax = tfFax.getText();
				String sitioWeb = tfSitioWeb.getText();

				String nomCompleto = tfNombre.getText();
				String correo = tfCorreo.getText();
				String cargo = tfCargo.getText();
				String telContacto = tfTelefonoContacto.getText();
				Contacto contacto = new Contacto(nit, nomCompleto, correo, cargo, telContacto);
				Empresa empresa = new Empresa(nit, sector, ciudad, contacto, razon, telEmpresa, tipoEmpresa, fax,
						sitioWeb, direccion);
				contacto.setEmpresa(empresa);

				controlador.editarContacto(contacto);
				controlador.editarEmpresa(empresa);
				JOptionPane.showMessageDialog(null, "Se edito correctamente la empresa");
			} catch (ExcepcionNegocio e1) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(null, e1.getMessage());
				e1.printStackTrace();

			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
	}
}
