/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.egresados.vista.gui;

import java.awt.Color;

import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Facultad;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.egresados.vista.controladores.ControladorVentanaGestionFacultad;

/**
 *
 * @author vanegas
 */
public class VentanaGestionFacultad extends javax.swing.JFrame {

	private ControladorVentanaGestionFacultad controlador;

	/**
	 * Creates new form VentanaGestionPrograma
	 */
	public VentanaGestionFacultad() {
		controlador = new ControladorVentanaGestionFacultad();
		initComponents();
		this.getContentPane().setBackground(Color.GREEN);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		tfCodigo = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		taDescripcion = new javax.swing.JTextArea();
		jPanel2 = new javax.swing.JPanel();
		btnGuardar = new javax.swing.JButton();
		btnEditar = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(0, 153, 0));
		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jLabel1.setText("Nombre de la facultad *");

		jLabel2.setText("Codigo *");

		jLabel3.setText("Descripcion *");

		taDescripcion.setColumns(20);
		taDescripcion.setRows(5);
		jScrollPane1.setViewportView(taDescripcion);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addGap(34, 34, 34)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jLabel1).addComponent(jLabel2)
														.addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE,
																190, Short.MAX_VALUE)
														.addComponent(tfCodigo))
												.addGap(53, 53, 53)
												.addGroup(
														jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel3).addComponent(jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 233,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(31, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(41, 41, 41)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(50, Short.MAX_VALUE)));

		jPanel2.setBackground(new java.awt.Color(0, 153, 0));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
		btnGuardar.setText("GUARDAR");
		btnGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGuardarActionPerformed(evt);
			}
		});

		btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
		btnEditar.setText("EDITAR");
		btnEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEditarActionPerformed(evt);
			}
		});

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupita.png"))); // NOI18N
		btnBuscar.setText("BUSCAR");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(21, 21, 21).addComponent(btnGuardar)
						.addGap(81, 81, 81).addComponent(btnBuscar)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnEditar).addGap(27, 27, 27)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnGuardar).addComponent(btnBuscar).addComponent(btnEditar))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abogado.png"))); // NOI18N

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrategia.png"))); // NOI18N
		jLabel6.setText("Gestion de facultades");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(21, 21, 21)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel5)
								.addGap(139, 139, 139).addComponent(jLabel6)))
				.addContainerGap(22, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(28, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup().addComponent(jLabel5).addGap(18,
																18, 18))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup().addComponent(jLabel6).addGap(32,
																32, 32)))
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(38, 38, 38)
										.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(27, 27, 27)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
		// TODO add your handling code here:
		try {
			if(tfCodigo.getText().isEmpty()||tfNombre.getText().isEmpty()||taDescripcion.getText().isEmpty()){
				JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
			}else{
			String codigo = tfCodigo.getText();
			String nombre = tfNombre.getText();
			String descrip = taDescripcion.getText();
			Facultad f = new Facultad(codigo, nombre, descrip);
			controlador.crearFacultad(f);
			JOptionPane.showMessageDialog(null, "Se creo correctamente la facultad "+nombre);
			limpiarCampos();
			}
		} catch (ExcepcionNegocio e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, e.getMessage());
			e.printStackTrace();
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}// GEN-LAST:event_btnGuardarActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		// TODO add your handling code here:
		try {
			Facultad f = controlador.buscarFacultad(tfCodigo.getText());
			if(f!=null){
				tfNombre.setText(f.getNombre());
				taDescripcion.setText(f.getDescripcion());
				
			}else{
				JOptionPane.showMessageDialog(null, "No se encontro la facultad con el codigo "+tfCodigo.getText());
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
		// TODO add your handling code here:
		try {
			String codigo = tfCodigo.getText();
			String nombre = tfNombre.getText();
			String descrip = taDescripcion.getText();
			Facultad f = new Facultad(codigo, nombre, descrip);
			controlador.editarFacultad(f);
			JOptionPane.showMessageDialog(null, "Se edito correctamente la facultad ");
			
		} catch (ExcepcionNegocio e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, e.getMessage());
			e.printStackTrace();
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnEditarActionPerformed
	public void limpiarCampos() {
		tfCodigo.setText(null);
		tfNombre.setText(null);
		taDescripcion.setText(null);;
	}
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnEditar;
	private javax.swing.JButton btnGuardar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea taDescripcion;
	private javax.swing.JTextField tfCodigo;
	private javax.swing.JTextField tfNombre;
	// End of variables declaration//GEN-END:variables
}
