/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.egresados.vista.gui;

import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.AreaInteres;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.AreasEgresado;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Egresado;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Facultad;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.InformacionAcademica;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.InformacionLaboral;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Programa;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.SectorLaboral;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.GeneroEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.MaximoNivelEduEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.MesEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.SituacionLaboralEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.TipoCorreoEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.TipoDocumentoEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.TipoEmpresaEnum;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.enumeraciones.TipoTelefonoEnum;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.egresados.vista.controladores.ControladorVentanaRegistroEgresados;

import java.awt.Color;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author 414pc04
 */
public class VentanaEditarEgresado extends javax.swing.JFrame {

	private ControladorVentanaRegistroEgresados controlador;
	private int numPagina = 0;

	/**
	 * Creates new form VentanaEditarEgresado
	 */
	public VentanaEditarEgresado() {
		initComponents();
		this.getContentPane().setBackground(Color.orange);
		cargarTipoDocumento();
		cargarTipoCorreo();
		cargarGenero();
		cargarTipoTelefono();
		cargarMaximoNivelEducacion();
		cargarMes();
		cargarSituacionLaboral();
		cargarTipoEmpresa();
		btnAtras.setVisible(false);
		btnEditar.setVisible(false);
		controlador = new ControladorVentanaRegistroEgresados();
		try {
			cargarComboFacultad();
			cargarComboAreaInteres();
			cargarComboSectorLaboral();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Método para llenar el combo de programa
	 * 
	 * @param facultad,
	 *            facultad ala cual pertenecen los programas
	 * @throws Exception
	 */
	private void llenarComboPrograma(String facultad) throws Exception {
		cbPrograma.removeAllItems();
		List<Programa> programas = controlador.listarPrograma(facultad);
		cbPrograma.addItem("Seleccione un programa");
		for (Programa programa : programas) {
			cbPrograma.addItem(programa);
		}
	}
	
	/**
	 * Método para llenar el combo de facultad
	 * 
	 * @throws Exception
	 */
	private void cargarComboFacultad() throws Exception {

		List<Facultad> facultades = controlador.listarFacultad();
		cbFacultad.addItem("Seleccione una facultad");
		for (Facultad facultad : facultades) {
			cbFacultad.addItem(facultad);
			// cbFacultad.addItem(facultad.getCodigo()+" -
			// "+facultad.getNombre());
		}
	}
	
	/**
	 * Método para llenar el combo de area de interes
	 * 
	 * @throws Exception
	 */
	private void cargarComboAreaInteres() throws Exception {

		List<AreaInteres> areasInteres = controlador.listarAreasInteres();
		cbAreasInteres.addItem("Seleccione un area de interes");
		for (AreaInteres areaInteres : areasInteres) {
			cbAreasInteres.addItem(areaInteres);
		}
	}

	/**
	 * Método para llenar el combo de sector laboral
	 * 
	 * @throws Exception
	 */
	private void cargarComboSectorLaboral() throws Exception {
		// cbPais.removeAllItems();
		List<SectorLaboral> sectores = controlador.listarSectoresLaborales();
		cbSectorLaboral.addItem("Seleccione un sector laboral");
		for (SectorLaboral sector : sectores) {
			cbSectorLaboral.addItem(sector);
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLPasos = new javax.swing.JLabel();
        jTPEgresados = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPrimerApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSegundoApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPrefijo = new javax.swing.JTextField();
        tfNumeroTel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfExtension = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox();
        tfNumeroDocumento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbTipoTelefono = new javax.swing.JComboBox();
        jRBFijo = new javax.swing.JRadioButton();
        jRBMovil = new javax.swing.JRadioButton();
        tfCorreo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbTipoCorreo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        cbMaximoNivelEducativo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cbPrograma = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbNivelAcademicoPrograma = new javax.swing.JTextField();
        jSFechaGrado = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        tfNumeroDiploma = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cbFacultad = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbSituacionLaboral = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        cbTipoEmpresa = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        cbSectorLaboral = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jDFechaIngreso = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jDFechaSalida = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        cbAreasInteres = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cientifico.png"))); // NOI18N

        jLPasos.setText("Paso 1/3");

        jTPEgresados.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel3.setText("Nombres*");

        jLabel4.setText("Primer Apellido*");

        jLabel5.setText("Segundo Apellido");

        jLabel6.setText("Telefono de Contacto*");

        jLabel7.setText("Prefijo");

        jLabel8.setText("Número*");

        jLabel9.setText("Extensión");

        jLabel10.setText("Tipo de Documento*");

        jLabel11.setText("Número*");

        jLabel12.setText("Genero*");

        jLabel13.setText("Tipo de Telefono");

        jRBFijo.setBackground(new java.awt.Color(255, 204, 102));
        jRBFijo.setText("Fijo");

        jRBMovil.setBackground(new java.awt.Color(255, 204, 102));
        jRBMovil.setText("Movil");

        jLabel14.setText("Correo Electrónico*");

        jLabel15.setText("Tipo de Correo*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNombres, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfPrimerApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPrefijo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(tfNumeroTel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(tfExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tfSegundoApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(cbGenero, 0, 180, Short.MAX_VALUE)
                    .addComponent(tfNumeroDocumento)
                    .addComponent(cbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTipoTelefono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBFijo)
                            .addComponent(jRBMovil)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(tfCorreo)
                            .addComponent(jLabel15)
                            .addComponent(cbTipoCorreo, 0, 172, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(26, 26, 26))))
                                .addComponent(cbTipoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(26, 26, 26)))
                    .addComponent(cbGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfNumeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBFijo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBMovil)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTPEgresados.addTab("1. Datos personales", new javax.swing.ImageIcon(getClass().getResource("/imagenes/hombre-de-negocios-papel-de-datos-personales.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        jLabel17.setText("Facultad*");

        jLabel18.setText("Programa*");

        jLabel19.setText("Nivel Academico del Programa");

        jSFechaGrado.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2016, 1));

        jLabel20.setText("Fecha de Grado*");

        jLabel21.setText("Número del Diploma*");

        jLabel22.setText("Máximo Nivel Educativo*");

        cbFacultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFacultadItemStateChanged(evt);
            }
        });

        jLabel26.setText("Mes*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(cbPrograma, 0, 180, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(cbNivelAcademicoPrograma)
                    .addComponent(cbFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSFechaGrado))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel21)
                    .addComponent(tfNumeroDiploma)
                    .addComponent(jLabel22)
                    .addComponent(cbMaximoNivelEducativo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel20)
                        .addComponent(jLabel26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cbPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumeroDiploma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNivelAcademicoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMaximoNivelEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTPEgresados.addTab("2. Educacion", new javax.swing.ImageIcon(getClass().getResource("/imagenes/birrete.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        jLabel23.setText("Situacion LaboralActual*");

        jLabel24.setText("Tipo de Empresa*");

        jLabel25.setText("Sector Laboral*");

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Ingreso"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Salida"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel28.setText("Área de conocimiento interesada*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(cbSituacionLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(cbTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(cbSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel28)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cbAreasInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(cbTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel23))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(cbSituacionLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(cbSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(cbAreasInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jTPEgresados.addTab("3. Ocupacion actual", new javax.swing.ImageIcon(getClass().getResource("/imagenes/laboral.png")), jPanel3); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-izquierda.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha-derecha.png"))); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contratoww.png"))); // NOI18N
        jLabel1.setText("Editor de egresados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLPasos)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTPEgresados)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(74, 74, 74)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel16))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLPasos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTPEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnAtras)
                    .addComponent(btnSiguiente)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    	
    	try {
				String documento = tfNumeroDocumento.getText();
				// Informacion Academica
				Facultad facultad = (Facultad) cbFacultad.getSelectedItem();
				Programa programa = (Programa) cbPrograma.getSelectedItem();
				String nivelAcademicoProg = cbNivelAcademicoPrograma.getText();
				int fecha = (Integer) jSFechaGrado.getValue();
				MesEnum mes = (MesEnum) cbMes.getSelectedItem();
				String numeroDiploma = tfNumeroDiploma.getText();
				MaximoNivelEduEnum maximoNivelEdu = (MaximoNivelEduEnum) cbMaximoNivelEducativo.getSelectedItem();

				InformacionAcademica infoAcademica = new InformacionAcademica(documento, facultad, programa,
						nivelAcademicoProg, fecha, mes, numeroDiploma, maximoNivelEdu);

				// Informacion Laboral
				SituacionLaboralEnum situcaionLaboral = (SituacionLaboralEnum) cbSituacionLaboral.getSelectedItem();
				TipoEmpresaEnum tipoEmpresa = (TipoEmpresaEnum) cbTipoEmpresa.getSelectedItem();
				SectorLaboral sectorLaboral = (SectorLaboral) cbSectorLaboral.getSelectedItem();
				Date fechaIngreso = jDFechaIngreso.getDate();
				Date fechaSalida = jDFechaSalida.getDate();
				InformacionLaboral infoLaboral = new InformacionLaboral(documento, situcaionLaboral, tipoEmpresa,
						sectorLaboral, "no se", fechaIngreso, fechaSalida, "no se");

				// Egresado
				String nombres = tfNombres.getText();
				String primerApellido = tfPrimerApellido.getText();
				TipoDocumentoEnum tipoDocumento = (TipoDocumentoEnum) cbTipoDocumento.getSelectedItem();
				String segundoApellido = tfSegundoApellido.getText();
				String telefono = tfPrefijo.getText() +" - "+ tfNumeroTel.getText() +" - "+ tfExtension.getText();
				GeneroEnum genero = (GeneroEnum) cbGenero.getSelectedItem();
				TipoTelefonoEnum tipoTelefono = (TipoTelefonoEnum) cbTipoTelefono.getSelectedItem();
				String correo = tfCorreo.getText();
				TipoCorreoEnum tipoCorreo = (TipoCorreoEnum) cbTipoCorreo.getSelectedItem();

				Egresado egresado = new Egresado(documento, programa, nombres, primerApellido, segundoApellido,
						tipoDocumento, genero, correo, tipoCorreo, telefono, tipoTelefono, infoAcademica, infoLaboral);

				// Area de Egresado
				AreaInteres area = (AreaInteres) cbAreasInteres.getSelectedItem();
				AreasEgresado areaEgresado = new AreasEgresado(egresado, area);

				infoAcademica.setEgresado(egresado);
				infoLaboral.setEgresado(egresado);
				controlador.editarEgresado(egresado);
				controlador.editarAreaEgresado(areaEgresado);
				controlador.editarInformacionLaboral(infoLaboral);
				controlador.editarInformacionAcademica(infoAcademica);

				JOptionPane.showMessageDialog(null, "Se edito correctamente el egresado");
		} catch (ExcepcionNegocio e1) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, e1.getMessage());
			e1.printStackTrace();
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
    	
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    	try {
    		String ced = tfNumeroDocumento.getText();
			Egresado egre = controlador.buscarEgresado(ced);
			
			if(egre != null){
				//primera pestaña -> Datos personales
				tfNombres.setText(egre.getNombre());
				tfPrimerApellido.setText(egre.getPrimerApellido());
				tfSegundoApellido.setText(egre.getSegundoApellido());
				tfCorreo.setText(egre.getEmail());
				String[] datos = egre.getTelefono().split(" - ");
				tfPrefijo.setText(datos[0]);
				tfNumeroTel.setText(datos[1]);
				tfExtension.setText(datos[2]);			
				cbTipoDocumento.setSelectedItem(egre.getTipoDocumento());
				tfNumeroDocumento.setText(egre.getCedula());
				cbGenero.setSelectedItem(egre.getGenero());
				cbTipoTelefono.setSelectedItem(egre.getTipoTelefono());
				cbTipoCorreo.setSelectedItem(egre.getTipoEmail());
				
				//Segunda pestaña -> Educacion
				cbFacultad.setSelectedItem(egre.getPrograma().getFacultad());
				cbPrograma.setSelectedItem(egre.getPrograma());
				cbNivelAcademicoPrograma.setText(egre.getInfoAcademica().getNivelAcademico());
				jSFechaGrado.setValue(egre.getInfoAcademica().getFechaGrado());
				cbMes.setSelectedItem(egre.getInfoAcademica().getMesGrado());
				tfNumeroDiploma.setText(egre.getInfoAcademica().getNumeroDiploma());
				cbMaximoNivelEducativo.setSelectedItem(egre.getInfoAcademica().getMaximoNivelEducativo());
				
				//Tercer pestaña -> Ocupacion Actual
				cbSituacionLaboral.setSelectedItem(egre.getInfoLaboral().getSituacionAct());
				cbTipoEmpresa.setSelectedItem(egre.getInfoLaboral().getTipoEmpresa());
				cbSectorLaboral.setSelectedItem(egre.getInfoLaboral().getSectLaboral());
				jDFechaIngreso.setDate(egre.getInfoLaboral().getFechaIngreso());
				jDFechaSalida.setDate(egre.getInfoLaboral().getFechaSalida());
			}else{
				JOptionPane.showMessageDialog(null, "El egresado con documeto "+ced+" no se encuentra registrado en la base de datos");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnBuscarActionPerformed

	private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtrasActionPerformed
		// TODO add your handling code here:
		numPagina--;
		jLPasos.setText("Paso " + (numPagina + 1) + "/3");
		jTPEgresados.setSelectedIndex(numPagina);
		btnSiguiente.setVisible(true);
		if (numPagina == 0) {
			btnAtras.setVisible(false);
		}
		btnEditar.setVisible(false);
	}// GEN-LAST:event_btnAtrasActionPerformed

	private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSiguienteActionPerformed
		numPagina++;
		jLPasos.setText("Paso " + (numPagina + 1) + "/3");
		jTPEgresados.setSelectedIndex(numPagina);
		btnAtras.setVisible(true);
		if (numPagina == 2) {
			btnSiguiente.setVisible(false);
			btnEditar.setVisible(true);
		}
	}// GEN-LAST:event_btnSiguienteActionPerformed

	private void cbFacultadItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbFacultadItemStateChanged
		// TODO add your handling code here:
		try {
			if (cbFacultad.getSelectedItem() == null) {
				return;
			}
			if (cbFacultad.getSelectedIndex() != 0) {
				Facultad facu = (Facultad) cbFacultad.getSelectedItem();
				// String datos[] = facu.split(" - ");
				llenarComboPrograma(facu.getCodigo());
			}
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
			ex.printStackTrace();
		}
	}// GEN-LAST:event_cbFacultadItemStateChanged

	public void cargarTipoDocumento() {
		for (TipoDocumentoEnum lista : TipoDocumentoEnum.values()) {
			cbTipoDocumento.addItem(lista);
		}
	}

	public void cargarTipoCorreo() {
		for (TipoCorreoEnum lista : TipoCorreoEnum.values()) {
			cbTipoCorreo.addItem(lista);
		}
	}

	public void cargarGenero() {
		for (GeneroEnum lista : GeneroEnum.values()) {
			cbGenero.addItem(lista);
		}
	}

	public void cargarTipoTelefono() {
		for (TipoTelefonoEnum lista : TipoTelefonoEnum.values()) {
			cbTipoTelefono.addItem(lista);
		}
	}

	public void cargarMaximoNivelEducacion() {
		for (MaximoNivelEduEnum lista : MaximoNivelEduEnum.values()) {
			cbMaximoNivelEducativo.addItem(lista);
		}
	}

	public void cargarMes() {
		for (MesEnum lista : MesEnum.values()) {
			cbMes.addItem(lista);
		}
	}

	public void cargarSituacionLaboral() {
		for (SituacionLaboralEnum lista : SituacionLaboralEnum.values()) {
			cbSituacionLaboral.addItem(lista);
		}
	}

	public void cargarTipoEmpresa() {
		for (TipoEmpresaEnum lista : TipoEmpresaEnum.values()) {
			cbTipoEmpresa.addItem(lista);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox cbAreasInteres;
    private javax.swing.JComboBox cbFacultad;
    private javax.swing.JComboBox cbGenero;
    private javax.swing.JComboBox cbMaximoNivelEducativo;
    private javax.swing.JComboBox cbMes;
    private javax.swing.JTextField cbNivelAcademicoPrograma;
    private javax.swing.JComboBox cbPrograma;
    private javax.swing.JComboBox cbSectorLaboral;
    private javax.swing.JComboBox cbSituacionLaboral;
    private javax.swing.JComboBox cbTipoCorreo;
    private javax.swing.JComboBox cbTipoDocumento;
    private javax.swing.JComboBox cbTipoEmpresa;
    private javax.swing.JComboBox cbTipoTelefono;
    private com.toedter.calendar.JDateChooser jDFechaIngreso;
    private com.toedter.calendar.JDateChooser jDFechaSalida;
    private javax.swing.JLabel jLPasos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRBFijo;
    private javax.swing.JRadioButton jRBMovil;
    private javax.swing.JSpinner jSFechaGrado;
    private javax.swing.JTabbedPane jTPEgresados;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfExtension;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfNumeroDiploma;
    private javax.swing.JTextField tfNumeroDocumento;
    private javax.swing.JTextField tfNumeroTel;
    private javax.swing.JTextField tfPrefijo;
    private javax.swing.JTextField tfPrimerApellido;
    private javax.swing.JTextField tfSegundoApellido;
    // End of variables declaration//GEN-END:variables
}
