/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.egresados.vista.gui;

import java.awt.Color;
import java.util.List;

import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Facultad;
import co.edu.eam.ingesoft.desarrollo.egresados.persistencia.modelo.entidades.Programa;
import co.edu.eam.ingesoft.desarrollo.logica.excepcion.ExcepcionNegocio;
import co.edu.eam.ingesoft.egresados.vista.controladores.ControladorVentanaGestionPrograma;

/**
 *
 * @author vanegas
 */
public class VentanaGestionPrograma extends javax.swing.JFrame {

	private ControladorVentanaGestionPrograma controlador;

	/**
	 * Creates new form VentanaGestionPrograma
	 */
	public VentanaGestionPrograma() {
		controlador = new ControladorVentanaGestionPrograma();
		initComponents();
		this.getContentPane().setBackground(Color.GREEN);
		try {
			cargarComboFacultad();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Método para llenar el combo de facultad
	 * 
	 * @throws Exception
	 */
	private void cargarComboFacultad() throws Exception {
		// cbPais.removeAllItems();
		List<Facultad> facultades = controlador.listarFacultad();
		cbFacultad.addItem("Seleccione una facultad");
		for (Facultad facultad : facultades) {
			cbFacultad.addItem(facultad.getCodigo()+" - "+facultad.getNombre());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		cbTipoPrograma = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		tfCodigo = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		taDescripcion = new javax.swing.JTextArea();
		jLabel8 = new javax.swing.JLabel();
		cbFacultad = new javax.swing.JComboBox<>();
		jPanel2 = new javax.swing.JPanel();
		btnRegistrar = new javax.swing.JButton();
		btnEditar = new javax.swing.JButton();
		btnBuscar = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		cbTipoPrograma.setBackground(new java.awt.Color(0, 153, 0));
		cbTipoPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jLabel1.setText("Nombre del programa *");

		jLabel2.setText("Codigo *");

		jLabel3.setText("Descripcion *");

		taDescripcion.setColumns(20);
		taDescripcion.setRows(5);
		jScrollPane1.setViewportView(taDescripcion);

		jLabel8.setText("Facultad *");

		javax.swing.GroupLayout cbTipoProgramaLayout = new javax.swing.GroupLayout(cbTipoPrograma);
		cbTipoPrograma.setLayout(cbTipoProgramaLayout);
		cbTipoProgramaLayout
				.setHorizontalGroup(
						cbTipoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										cbTipoProgramaLayout.createSequentialGroup().addGap(34, 34, 34)
												.addGroup(cbTipoProgramaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(cbFacultad, 0, 190, Short.MAX_VALUE)
														.addComponent(jLabel1).addComponent(jLabel2)
														.addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE,
																190, Short.MAX_VALUE)
														.addComponent(tfCodigo).addComponent(jLabel8))
												.addGap(53, 53, 53)
												.addGroup(
														cbTipoProgramaLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel3).addComponent(jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 233,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)));
		cbTipoProgramaLayout.setVerticalGroup(cbTipoProgramaLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(cbTipoProgramaLayout.createSequentialGroup().addGap(41, 41, 41)
						.addGroup(cbTipoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(cbTipoProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(cbTipoProgramaLayout.createSequentialGroup()
										.addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel8)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(cbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(24, Short.MAX_VALUE)));

		jPanel2.setBackground(new java.awt.Color(0, 153, 0));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
		btnRegistrar.setText("REGISTRAR");
		btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRegistrarActionPerformed(evt);
			}
		});

		btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
		btnEditar.setText("EDITAR");
		btnEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnEditarActionPerformed(evt);
			}
		});

		btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupita.png"))); // NOI18N
		btnBuscar.setText("BUSCAR");
		btnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBuscarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(25, 25, 25).addComponent(btnRegistrar)
						.addGap(76, 76, 76).addComponent(btnBuscar).addGap(78, 78, 78).addComponent(btnEditar)
						.addContainerGap(31, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnRegistrar).addComponent(btnBuscar).addComponent(btnEditar))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abogado.png"))); // NOI18N

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrategia.png"))); // NOI18N
		jLabel6.setText("Gestion programa academico");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(21, 21, 21)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(cbTipoPrograma, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addGap(57, 57, 57).addComponent(jLabel5)
								.addGap(102, 102, 102).addComponent(jLabel6)))
				.addContainerGap(15, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup().addContainerGap(24, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup().addComponent(jLabel6).addGap(41,
																41, 41))
												.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cbTipoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(32, 32, 32)
										.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(27, 27, 27)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarActionPerformed
		// TODO add your handling code here:
		try {
			if (tfCodigo.getText().isEmpty() || tfNombre.getText().isEmpty() || taDescripcion.getText().isEmpty()||cbFacultad.getSelectedIndex()==0) {
				JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
			} else {
				String codigo = tfCodigo.getText();
				String nombre = tfNombre.getText();
				String descrip = taDescripcion.getText();
				String facu = (String) cbFacultad.getSelectedItem();
				String datos[] = facu.split(" - ");
				Facultad facultad = controlador.buscarFacultad(datos[0]);
				Programa programa = new Programa(codigo, facultad, nombre, descrip);
				controlador.crearPrograma(programa);
				JOptionPane.showMessageDialog(null, "Se creo correctamente el programa " + nombre);
				limpiarCampos();
			}
		} catch (ExcepcionNegocio e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, e.getMessage());
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnRegistrarActionPerformed

	private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
		// TODO add your handling code here:
		try {
			Programa p = controlador.buscarPrograma(tfCodigo.getText());
			if (p != null) {
				tfNombre.setText(p.getNombre());
				taDescripcion.setText(p.getDescripcion());

			} else {
				JOptionPane.showMessageDialog(null, "No se encontro el programa con el codigo " + tfCodigo.getText());
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnBuscarActionPerformed

	private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
		// TODO add your handling code here:
		try {
			String codigo = tfCodigo.getText();
			String nombre = tfNombre.getText();
			String descrip = taDescripcion.getText();
			String facu = (String) cbFacultad.getSelectedItem();
			String datos[] = facu.split(" - ");
			Facultad facultad = controlador.buscarFacultad(datos[0]);
			Programa programa = new Programa(codigo, facultad, nombre, descrip);
			controlador.editarPrograma(programa);
			JOptionPane.showMessageDialog(null, "Se edito correctamente el programa ");

		} catch (ExcepcionNegocio e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, e.getMessage());
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}// GEN-LAST:event_btnEditarActionPerformed

	public void limpiarCampos() {
		tfCodigo.setText(null);
		tfNombre.setText(null);
		taDescripcion.setText(null);
		cbFacultad.setSelectedIndex(0);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnBuscar;
	private javax.swing.JButton btnEditar;
	private javax.swing.JButton btnRegistrar;
	private javax.swing.JComboBox<String> cbFacultad;
	private javax.swing.JPanel cbTipoPrograma;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea taDescripcion;
	private javax.swing.JTextField tfCodigo;
	private javax.swing.JTextField tfNombre;
	// End of variables declaration//GEN-END:variables
}
